plugins {
	id 'java'
}

apply from: 'dependencies.gradle'

repositories {
	mavenCentral()
}

tasks.withType(Test).configureEach {
	useJUnitPlatform()
}

configurations.configureEach {
	exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
}

dependencies {
	annotationProcessor libs.lombok
	implementation libs.lombok
	implementation springBootDeps
	implementation loggingDeps

	testImplementation (libs.springbootTest){
		exclude group: "junit", module: "junit"
	}
	testImplementation libs.springSecTest
	testImplementation libs.springBootSecTest
	testImplementation libs.springBootWebMvcTest
	testImplementation libs.junit5
	testRuntimeOnly libs.junitplatform
}

test {
	useJUnitPlatform()
}
